openapi: 3.0.0
info:
  version: 1.0.0
  title: My demo App
paths:
  /api/methodes/{method}:
    get:
      summary: Get method info
      operationId: getMethod
      parameters:
        - name: method
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: An method
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Method'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Method:
      required:
        - id
        - name
        - image
        - figurativeMark
        - figurativeMarkSmall
      properties:
        id:
          type: string
        param:
          type: string
        image:
          type: string
        figurativeMark:
          type: string
        figurativeMarkSmall:
          type: string
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
